function(openjk_add_jolt)
	set(CMAKE_POLICY_DEFAULT_CMP0077 NEW)
	set(FETCHCONTENT_BASE_DIR "${CMAKE_BINARY_DIR}/cache" CACHE PATH "FetchContent cache directory")
	include(FetchContent)
	foreach(feature BUILD_SHARED_LIBS OVERRIDE_CXX_FLAGS INTERPROCEDURAL_OPTIMIZATION
		GENERATE_DEBUG_SYMBOLS ENABLE_ALL_WARNINGS ENABLE_INSTALL ENABLE_OBJECT_STREAM
		DEBUG_RENDERER_IN_DEBUG_AND_RELEASE PROFILER_IN_DEBUG_AND_RELEASE
		USE_SSE4_1 USE_SSE4_2 USE_AVX USE_AVX2 USE_AVX512 USE_LZCNT USE_TZCNT USE_F16C USE_FMADD)
		set(${feature} OFF)
	endforeach()
	set(USE_STATIC_MSVC_RUNTIME_LIBRARY OFF)
	FetchContent_Declare(jolt
		URL https://codeload.github.com/jrouwe/JoltPhysics/tar.gz/refs/tags/v5.3.0
		URL_HASH SHA256=e7f9621e480646c434150e1fbe3a9410f4ec4b04ffe54791e0678326b741b918
		SOURCE_SUBDIR Build
		EXCLUDE_FROM_ALL)
	FetchContent_MakeAvailable(jolt)
	install(FILES "${jolt_SOURCE_DIR}/LICENSE"
		DESTINATION "${JKASPInstallDir}/licenses/jolt" COMPONENT ${JKASPClientComponent})
endfunction()
